spring:
  datasource:
    url: jdbc:mysql://13.209.98.208:3306/glym_spring_test?useSSL=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 7904
    driver-class-name: com.mysql.cj.jdbc.Driver